name: Bug Report
description: Report a bug in Boxicons
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear and concise description of what the bug is.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS:
        - Browser:
        - Version:
